### PR TITLE
Update admin records

### PR DESCRIPTION
**Pull request by stepps00**
Replaces https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/11

To do:
- [x] Update localadmin placetype
- [x] Update locality placetype (inc. concordances)
- [x] Add `src:geom_via` to localadmin
- [x] For deprecated locality polygons, supersede into new localadmin when needed (ex: Wellington)
- [x] Supersede neighbourhood records into current localities when needed
- [x] Update `lbl:bbox`/`coterminous` properties on locality records to match `lbl:bbox` of parent localadmin records with the same name
- [x] Ensure source properties are applied to each new locality record (name, id, placetype)
- [x] Convert existing, leftover neighbourhood polygons to points
- [x] Update `mz:is_landuse_aoi` properties on park preserves
- [x] Ensure new Point geometries have `lbl:bbox` properties
- [x] Ensure records have `wof:geom_alt` properties
- [x] Import new lang properties
- [x] Import smaller costal bay features as neighbourhood records (`mz:is_landuse_aoi` = 1)
- [x] Update marinearea placetype (merged coastal bays, `mz:is_landuse_aoi` = 1) (larger in XY, note size cutoff)
  - XY repo: https://github.com/whosonfirst-data/whosonfirst-data-admin-xy/pull/23
- [x] Create six new locality points near the "* Central" localities. Should have the lbl bbox and name of the localadmin parent. These places would be coterminous w the parent localadmin, min_zoom of localadmin/county.
- [x] Mark leftover neighbourhood points as is_funky = 1.
- [x] Update county hierarchy
- [x] QA the six "central" locality points and their neighboring polygons
- [x] Add name translations
- [x] PIP
- [x] Validate geometries, properties, and repo
- [x] Merge source file

### CODE REVIEW

**Comment by stepps00** [comment]
Commit Notes: 

c46ddd1: Deprecates existing localadmin points, as they do not match to features in the source files
aead635: Adds new localadmin records, which were created by merging features with matching `city_id` attributes in the `nz-linz` source. If more than one feature share the attribute, they were merged to create ~90 new localadmin records (which will parent suburbs).

**Comment by stepps00** [comment]
@nvkelso - this PR now includes PIP work and all changes we've previously talked about (see commit notes for detail).

I do want to QA ~a dozen locality records that represent the major cities in NZ, but this is ready to review.

**Comment by nvkelso** [comment]
For the 6 new localities that were added in https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/12/commits/fa526c7dd744d180359784db277de6a58b904949, it looks like we had localies for them before that we deprecated in https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/commit/ca5aa9f0ccebb26640bae02bd324703059b740fb. Just for those 6 let's resurrect the old polygon record's ID with all the details from the new point record (so those 6 places would have their old IDs and the intermediate files from the newer commit would be removed).

**Comment by stepps00** [comment]
> For the 6 new localities that were added in fa526c7, it looks like we had localies for them before that we deprecated in ca5aa9f. Just for those 6 let's resurrect the old polygon record's ID with all the details from the new point record (so those 6 places would have their old IDs and the intermediate files from the newer commit would be removed).

Yep, I noticed the same thing while processing this PR with the PIP tools.. I added an unchecked "to do" item in this PR: " QA the six "central" locality points and their neighboring polygons".

The last thing I need to do before merging is untangling these 6 (12?) records and making sure I'm not introducing duplicate records.

**Comment by nvkelso** [comment]
Please run wikidata names import and then let's call this done.

**Review by nvkelso — APPROVED** [review]

**Pull request merged**
