### PR TITLE
Update Place Wellington

### PR DESCRIPTION
**Pull request by nvkelso**
Updating `data/101/914/285/101914285.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Comment by nvkelso** [comment]
Move NE props and related zoom props from AU record to NZ record, paired with https://github.com/whosonfirst-data/whosonfirst-data-admin-au/pull/46.

**Comment by stepps00** [comment]
False alarm - it looks like the newer Go exportify tools also add a carriage return at the end of a record. Some recent PRs that have updated WOF records using the Go tools have been merged, none have caused issue.. so tldr: this can be merged as-is.

**Review by stepps00 — APPROVED** [review]
LGTM

**Comment by nvkelso** [comment]
Thanks for 2x checking! :)

**Pull request merged**
